# Generated by Django 5.2.14 on 2026-05-15 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Lab group',
                'verbose_name_plural': 'Lab groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('mpi_id', models.CharField(blank=True, max_length=64)),
                ('ahv_number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='LabParameter',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=50)),
                ('code_system', models.CharField(default='http://loinc.org', max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='lab_data.labgroup')),
            ],
            options={
                'verbose_name': 'Lab parameter',
                'verbose_name_plural': 'Lab parameters',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('lab_report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file_path', models.CharField(max_length=500)),
                ('source_type', models.CharField(choices=[('FHIR_JSON', 'FHIR JSON'), ('PDF', 'PDF')], max_length=20)),
                ('structured_data_json', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='lab_data.patient')),
            ],
            options={
                'verbose_name': 'Lab report',
                'verbose_name_plural': 'Lab reports',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='LabValue',
            fields=[
                ('lab_value_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measurement_date', models.DateTimeField()),
                ('measured_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('reference_range_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('reference_range_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('interpretation_code', models.CharField(blank=True, choices=[('L', 'Low'), ('N', 'Normal'), ('H', 'High'), ('LL', 'Critical low'), ('HH', 'Critical high'), ('A', 'Abnormal')], max_length=2)),
                ('lab_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='lab_data.labreport')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='lab_data.labparameter')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='lab_data.unit')),
            ],
            options={
                'verbose_name': 'Lab value',
                'verbose_name_plural': 'Lab values',
                'ordering': ['lab_report', 'parameter'],
            },
        ),
        migrations.AddConstraint(
            model_name='labparameter',
            constraint=models.UniqueConstraint(fields=('code', 'code_system'), name='unique_parameter_per_code_system'),
        ),
    ]
