# Generated by Django 5.2.14 on 2026-05-25 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('reference_range_id', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', max_length=10)),
                ('age_min_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('age_max_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('source', models.CharField(max_length=500)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='lab_data.labparameter')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_ranges', to='lab_data.unit')),
            ],
            options={
                'verbose_name': 'Reference range',
                'verbose_name_plural': 'Reference ranges',
                'ordering': ['parameter', 'sex', 'age_min_years'],
            },
        ),
    ]
